ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "password_hash" text;
UPDATE "users" SET "password_hash" = 'account-reset-required' WHERE "password_hash" IS NULL;
ALTER TABLE "users" ALTER COLUMN "password_hash" SET NOT NULL;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "university_verified" boolean NOT NULL DEFAULT false;
ALTER TABLE "users" ALTER COLUMN "latitude" SET DEFAULT 0;
ALTER TABLE "users" ALTER COLUMN "longitude" SET DEFAULT 0;
DO $$ BEGIN CREATE TYPE "public"."visibility" AS ENUM('public', 'campus', 'members'); EXCEPTION WHEN duplicate_object THEN null; END $$;
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "location" text NOT NULL DEFAULT 'Campus location';
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "visibility" "visibility" NOT NULL DEFAULT 'public';
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "image_url" text;
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "capacity" integer NOT NULL DEFAULT 100;
ALTER TABLE "events" ALTER COLUMN "start_date" TYPE timestamptz USING "start_date"::timestamp AT TIME ZONE 'UTC';
ALTER TABLE "events" ALTER COLUMN "end_date" TYPE timestamptz USING "end_date"::timestamp AT TIME ZONE 'UTC';
CREATE TABLE IF NOT EXISTS "event_rsvps" ("event_id" uuid NOT NULL REFERENCES "events"("event_id") ON DELETE cascade, "user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE cascade, "created_at" timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS "event_user_rsvp_idx" ON "event_rsvps" ("event_id", "user_id");
CREATE TABLE IF NOT EXISTS "notifications" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE cascade, "title" text NOT NULL, "body" text NOT NULL, "read" boolean NOT NULL DEFAULT false, "created_at" timestamptz NOT NULL DEFAULT now());
ALTER TABLE "group_chats" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "group_chats" ALTER COLUMN "adminOnly" SET DEFAULT false;
UPDATE "group_chats" SET "adminOnly" = false;
ALTER TABLE "messages" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "messages" ALTER COLUMN "sent_at" SET DEFAULT now();
INSERT INTO "group_chats" ("event_id", "adminOnly") SELECT "event_id", false FROM "events" ON CONFLICT ("event_id") DO NOTHING;
